version: "3.9"
services:
  mysql:
    restart: always
    container_name: "mysql"
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - $MYSQL_ROOT_PASSWORD
      - $MYSQL_DATABASE
      - $MYSQL_USER
      - $MYSQL_PASSWORD
