version: "3.9"
services:
  mysql:
    restart: always
    container_name: "mysql"
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=dbtest
      - MYSQL_USER=momo
      - MYSQL_PASSWORD=123456789
